### ISSUE TITLE
Compat with cherished worlds

### ISSUE THREAD

**Issue by mrmelon54** [MrMelon54/enhanced_searchability#3]
Add compat with [Cherished Worlds](https://modrinth.com/mod/cherished-worlds)

![image](https://user-images.githubusercontent.com/48031324/220387273-189e0193-246f-4b97-80f7-fcc54ee064a8.png)
![image](https://user-images.githubusercontent.com/48031324/220387292-e0448eea-d251-4456-8dfe-4b69fd1a76c1.png)

**Comment by UltimatChamp** [comment]
Works fine for me on 1.20.4!

![image](https://github.com/mrmelon54/enhanced_searchability/assets/140878474/ae5961af-a009-4ec1-be9c-290c83c97650)

**Comment by mrmelon54** [comment]
Thanks for letting me know
