### ISSUE TITLE
Resource-pack Seachbars Look Wierd

### ISSUE THREAD

**Issue by UltimatChamp** [MrMelon54/enhanced_searchability#5]
Enhanced Searchability `v1.0.4`

Extra search bar width by some pixels for both of the bars.
Different from the featured images on Modrinth.

Here's an old vs new comparison:
<img src="https://cdn.modrinth.com/data/Scg0CNUt/images/c310d6e97479fc83dd8fe7c205e1d43a00b2dd4f.png" width="400px"> <img src="https://github.com/mrmelon54/enhanced_searchability/assets/140878474/1447988d-8257-4c88-b7d2-7d927828c35a" width="400px">

Different screen widths also does not fix this. These bars seem to be stationary in the width-scale than the vanilla singleplayer searchbar.

**Comment by mrmelon54** [comment]
so the bars are the same relative size as the rest of the scaled UI components?

but obviously the bars are too wide

**Comment by mrmelon54** [comment]
Added to v1.0.5
